# configuration file for npg_qc_viewer Catalyst application
name npg_qc_viewer

<Model Check>
    use_db    1
</Model>

<Model GenotypeCheck>
    composite_results_loc    /nfs/sf32/qc/cgtck_results
</Model>

<Model LimsServer>
</Model>

<Plugin::Session>
    expires 3600
</Plugin::Session>
